[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root
pidfile=/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:minecraft]
directory=/data/minecraft
command=sh -c "/configure && java -XX:+UseG1GC -Xms6G -Xmx6G --enable-native-access=ALL-UNNAMED -jar "/spigot.jar" nogui --noconsole 2>&1"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
