version: '3.3'
services:
  server:
    build: ./image
    restart: unless-stopped
    volumes:
      - ./_:/data
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp

  upnp-client:
    build: ./upnp-client/image
    restart: unless-stopped
    network_mode: "host"
    environment:
      - UPNP_INTERVAL=600
      - UPNP_CONFIG=TCP 25565 25565;UDP 25565 25565