version: '3.3'
services:
  server:
    build: ./
    restart: always
    command: ["./init.sh"]
    volumes:
      - ../../data/minecraft/data:/data
      - ../../data/minecraft/jar:/jar
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
