version: '3.3'
services:
  server:
    build: ./image
    restart: always
    command: ["./init.sh"]
    volumes:
      - ./_/data:/data
      - ./_/jar:/jar
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
