#!/bin/bash
set -eo pipefail
#https://gist.github.com/vivien/3b1c2efb80f3f3dde001
USERNAME=$1
CHAN=#$2

SERVER=wings.keenetic.link
PORT=6667
INPUT=`mktemp --suffix .in`
OUTPUT=`mktemp --suffix .out`
IRC_CONNECTION_PID=

irc_login(){
        echo "USER $1 * * : $1"
        echo "NICK $1"
}

irc_join(){
        echo "JOIN $1"
}

irc_message(){
        echo "PRIVMSG $1 : $2"
}

irc_quit(){
        echo "QUIT"

}

SEQ=0
while read line; do
	SEQ=$((SEQ+1))
	USER=$USERNAME$SEQ
	echo -n > $INPUT
	echo -n > $OUTPUT
	{
			irc_login $USER
			irc_join $CHAN
			irc_message $CHAN "$line"
			irc_quit

	} | nc $SERVER $PORT &
	IRC_CONNECTION_PID=$!;
	wait
done

rm -f $INPUT $OUTPUT
